import jsPDF from 'jspdf';
import { DocumentType } from '@prisma/client';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface GenerateDocumentParams {
  documentType: string;
  requestId: string;
  memberName?: string;
  personName?: string; // Alias used by the approve route
  churchName: string;
  churchAddress?: string;
  churchCity?: string;
  churchCountry?: string;
  pastorName?: string;
  reason?: string;
  clerkNotes?: string;
  generatedAt?: Date;
  baseUrl?: string;
  documentExpiry?: Date;
  // Extra fields passed by approve route (ignored internally)
  memberId?: string;
  personId?: string;
  churchId?: string;
}

export interface GenerateDocumentResult {
  pdfData: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

function randomAlphanumeric(length: number): string {
  let result = '';
  const bytes = new Uint8Array(length);
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    crypto.getRandomValues(bytes);
    for (let i = 0; i < length; i++) {
      result += CHARS[bytes[i] % CHARS.length];
    }
  } else {
    for (let i = 0; i < length; i++) {
      result += CHARS[Math.floor(Math.random() * CHARS.length)];
    }
  }
  return result;
}

function resolveMemberName(params: GenerateDocumentParams): string {
  return params.memberName || params.personName || 'Unknown Member';
}

function resolveGeneratedAt(params: GenerateDocumentParams): Date {
  return params.generatedAt || new Date();
}

function resolveExpiry(params: GenerateDocumentParams): Date {
  if (params.documentExpiry) return params.documentExpiry;
  const d = new Date();
  d.setFullYear(d.getFullYear() + 1);
  return d;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function drawHeader(doc: jsPDF, churchName: string): void {
  // Church name header
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Seventh-day Adventist Church', 105, 15, { align: 'center' });

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(churchName, 105, 24, { align: 'center' });

  // Thin line separator
  doc.setDrawColor(26, 122, 86); // emerald
  doc.setLineWidth(0.5);
  doc.line(20, 29, 190, 29);
}

function drawDocIdAndDates(
  doc: jsPDF,
  requestId: string,
  generatedAt: Date,
  expiryDate: Date
): void {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Document ID: ${requestId}`, 20, 36);
  doc.text(`Generated: ${formatDate(generatedAt)}`, 20, 41);
  doc.text(`Expires: ${formatDate(expiryDate)}`, 20, 46);
  doc.setTextColor(0, 0, 0);
}

function drawFooter(doc: jsPDF): void {
  // Footer separator line
  const y = 280;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);

  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This document was generated by Adventify - Seventh-day Adventist Church Management System',
    105,
    y + 5,
    { align: 'center' }
  );
  doc.setTextColor(0, 0, 0);
}

function drawSignatureLine(doc: jsPDF, y: number, label?: string): void {
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(115, y, 185, y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(label || 'Authorized Signature', 150, y + 5, { align: 'center' });
  doc.setFontSize(8);
  doc.text('Date: _______________', 150, y + 12, { align: 'center' });
}

// ─── Request ID Generator ────────────────────────────────────────────────────

export function generateRequestId(): string {
  const year = new Date().getFullYear();
  const rand = randomAlphanumeric(8);
  return `REQ-${year}-${rand}`;
}

// ─── Main Dispatcher ────────────────────────────────────────────────────────

export async function generateDocumentPDF(
  params: GenerateDocumentParams
): Promise<GenerateDocumentResult> {
  const documentType = params.documentType as DocumentType;

  const generators: Record<
    DocumentType,
    (params: GenerateDocumentParams) => jsPDF
  > = {
    BAPTISM_CERTIFICATE: generateBaptismCertificate,
    INTRODUCTION_LETTER: generateIntroductionLetter,
    MEMBERSHIP_VERIFICATION: generateMembershipVerification,
    CHARACTER_REFERENCE: generateCharacterReference,
    SERVICE_CERTIFICATE: generateServiceCertificate,
  };

  const generator = generators[documentType];
  if (!generator) {
    throw new Error(`Unknown document type: ${documentType}`);
  }

  const doc = generator(params);
  const pdfData = doc.output('datauristring');
  return { pdfData };
}

// ─── Document Generators ─────────────────────────────────────────────────────

function generateBaptismCertificate(params: GenerateDocumentParams): jsPDF {
  const doc = new jsPDF();
  const memberName = resolveMemberName(params);
  const generatedAt = resolveGeneratedAt(params);
  const expiryDate = resolveExpiry(params);

  // Header
  drawHeader(doc, params.churchName);

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Baptism Certificate', 105, 60, { align: 'center' });

  // Decorative line under title
  doc.setDrawColor(26, 122, 86);
  doc.setLineWidth(0.8);
  doc.line(60, 64, 150, 64);

  // Body
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('This is to certify that', 105, 82, { align: 'center' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(memberName, 105, 96, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'has been baptized and received into the fellowship of the',
    105,
    112,
    { align: 'center' }
  );
  doc.text(params.churchName, 105, 120, { align: 'center' });
  doc.text(
    'Seventh-day Adventist Church.',
    105,
    128,
    { align: 'center' }
  );

  // Church location
  if (params.churchCity || params.churchCountry) {
    const location = [params.churchCity, params.churchCountry]
      .filter(Boolean)
      .join(', ');
    doc.setFontSize(10);
    doc.text(location, 105, 138, { align: 'center' });
  }

  // Baptism date
  doc.setFontSize(11);
  doc.text(`Date: ${formatDate(generatedAt)}`, 105, 152, { align: 'center' });

  // Reason / additional notes
  if (params.reason) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text(`"${params.reason}"`, 105, 164, { align: 'center' });
  }

  // Pastor name
  if (params.pastorName) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Officiating Pastor: ${params.pastorName}`, 30, 190);
  }

  // Clerk notes
  if (params.clerkNotes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    const lines = doc.splitTextToSize(params.clerkNotes, 70);
    doc.text(lines, 20, 210);
    doc.setTextColor(0, 0, 0);
  }

  // Signature
  drawSignatureLine(doc, 220, 'Pastor / Church Officer');

  // Doc ID & dates
  drawDocIdAndDates(doc, params.requestId, generatedAt, expiryDate);

  // Footer
  drawFooter(doc);

  return doc;
}

function generateIntroductionLetter(params: GenerateDocumentParams): jsPDF {
  const doc = new jsPDF();
  const memberName = resolveMemberName(params);
  const generatedAt = resolveGeneratedAt(params);
  const expiryDate = resolveExpiry(params);

  // Header (letterhead style)
  drawHeader(doc, params.churchName);

  // Church address
  if (params.churchAddress || params.churchCity || params.churchCountry) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    const addrParts = [
      params.churchAddress,
      params.churchCity,
      params.churchCountry,
    ].filter(Boolean);
    doc.text(addrParts.join(', '), 105, 35, { align: 'center' });
    doc.setTextColor(0, 0, 0);
  }

  // Date
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(formatDate(generatedAt), 20, 55);

  // Salutation
  doc.text('To Whom It May Concern,', 20, 68);

  // Body paragraphs
  doc.setFontSize(11);
  const bodyLines: string[] = [];

  bodyLines.push(
    `This letter is written on behalf of ${memberName}, who is a recognized member in good standing at ${params.churchName}, a Seventh-day Adventist Church.`
  );

  if (params.reason) {
    bodyLines.push(
      `${memberName} is requesting this letter for the following purpose: ${params.reason}.`
    );
  }

  bodyLines.push(
    `${memberName} has demonstrated consistent dedication to the faith, active participation in church activities, and upholds the values and principles of the Seventh-day Adventist Church.`
  );

  bodyLines.push(
    `We wholeheartedly recommend ${memberName} and affirm their character and commitment. Should you require any further information, please do not hesitate to contact us.`
  );

  let y = 82;
  for (const line of bodyLines) {
    const wrapped = doc.splitTextToSize(line, 170);
    for (const wl of wrapped) {
      doc.text(wl, 20, y);
      y += 6;
    }
    y += 4; // paragraph spacing
  }

  // Closing
  y += 6;
  doc.text('Sincerely,', 20, y);

  if (params.pastorName) {
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(params.pastorName, 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('Church Pastor', 20, y);
  }

  // Clerk notes
  if (params.clerkNotes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    const notesWrapped = doc.splitTextToSize(
      `Clerk Notes: ${params.clerkNotes}`,
      170
    );
    doc.text(notesWrapped, 20, y + 20);
    doc.setTextColor(0, 0, 0);
  }

  // Doc ID & dates
  drawDocIdAndDates(doc, params.requestId, generatedAt, expiryDate);

  // Footer
  drawFooter(doc);

  return doc;
}

function generateMembershipVerification(
  params: GenerateDocumentParams
): jsPDF {
  const doc = new jsPDF();
  const memberName = resolveMemberName(params);
  const generatedAt = resolveGeneratedAt(params);
  const expiryDate = resolveExpiry(params);

  // Header
  drawHeader(doc, params.churchName);

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Membership Verification Letter', 105, 60, { align: 'center' });

  // Decorative line
  doc.setDrawColor(26, 122, 86);
  doc.setLineWidth(0.8);
  doc.line(45, 64, 165, 64);

  // Verification badge
  doc.setFillColor(22, 163, 74); // emerald-600
  doc.roundedRect(72, 74, 66, 12, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('STATUS: ACTIVE', 105, 82, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  // Body
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'This letter confirms that the following individual is a verified,',
    20,
    100
  );
  doc.text(
    'active member in good standing of our church:',
    20,
    108
  );

  // Member name highlight
  doc.setFillColor(240, 253, 244); // emerald-50
  doc.roundedRect(25, 115, 160, 14, 2, 2, 'F');
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(memberName, 105, 124, { align: 'center' });

  // Church details
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  let y = 142;

  doc.text('Church:', 25, y);
  doc.setFont('helvetica', 'bold');
  doc.text(params.churchName, 60, y);
  y += 8;

  if (params.churchCity || params.churchCountry) {
    doc.setFont('helvetica', 'normal');
    doc.text('Location:', 25, y);
    doc.setFont('helvetica', 'bold');
    const loc = [params.churchCity, params.churchCountry]
      .filter(Boolean)
      .join(', ');
    doc.text(loc, 60, y);
    y += 8;
  }

  doc.setFont('helvetica', 'normal');
  doc.text('Verified On:', 25, y);
  doc.setFont('helvetica', 'bold');
  doc.text(formatDate(generatedAt), 60, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.text('Valid Until:', 25, y);
  doc.setFont('helvetica', 'bold');
  doc.text(formatDate(expiryDate), 60, y);

  // Verification statement
  y += 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  const statement = doc.splitTextToSize(
    'This verification is issued to confirm the membership status of the individual named above. The information provided is accurate to the best of our knowledge as of the date of issuance.',
    160
  );
  doc.text(statement, 20, y);

  // Clerk notes
  if (params.clerkNotes) {
    y += 18;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    const notesWrapped = doc.splitTextToSize(
      `Clerk Notes: ${params.clerkNotes}`,
      160
    );
    doc.text(notesWrapped, 20, y);
    doc.setTextColor(0, 0, 0);
  }

  // Signature
  drawSignatureLine(doc, 240, 'Church Clerk / Pastor');

  // Doc ID
  drawDocIdAndDates(doc, params.requestId, generatedAt, expiryDate);

  // Footer
  drawFooter(doc);

  return doc;
}

function generateCharacterReference(params: GenerateDocumentParams): jsPDF {
  const doc = new jsPDF();
  const memberName = resolveMemberName(params);
  const generatedAt = resolveGeneratedAt(params);
  const expiryDate = resolveExpiry(params);

  // Header
  drawHeader(doc, params.churchName);

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Character Reference Letter', 105, 60, { align: 'center' });

  // Decorative line
  doc.setDrawColor(26, 122, 86);
  doc.setLineWidth(0.8);
  doc.line(45, 64, 165, 64);

  // Date
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(formatDate(generatedAt), 20, 78);

  // Salutation
  doc.text('To Whom It May Concern,', 20, 90);

  // Body paragraphs
  const paragraphs: string[] = [];

  paragraphs.push(
    `On behalf of ${params.churchName}, we are pleased to provide this character reference for ${memberName}.`
  );

  paragraphs.push(
    `${memberName} has been an active and dedicated member of our congregation. They have consistently demonstrated exemplary conduct, integrity, and a genuine commitment to spiritual growth and community service.`
  );

  if (params.reason) {
    paragraphs.push(
      `We understand that this reference is being requested for the following purpose: ${params.reason}. We believe ${memberName} is well-suited for this endeavor.`
    );
  }

  paragraphs.push(
    `As a faith community, we have observed ${memberName}'s involvement in various church activities, their willingness to support others, and their adherence to Christian principles. They have earned the respect and trust of both church leadership and fellow members.`
  );

  paragraphs.push(
    `We recommend ${memberName} without reservation and are confident that they will continue to be an asset in any endeavor they undertake.`
  );

  let y = 102;
  for (const para of paragraphs) {
    const wrapped = doc.splitTextToSize(para, 170);
    for (const line of wrapped) {
      doc.text(line, 20, y);
      y += 6;
    }
    y += 5; // paragraph spacing
  }

  // Closing
  y += 4;
  doc.text('Warm regards,', 20, y);

  if (params.pastorName) {
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(params.pastorName, 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('Church Pastor', 20, y);
    y += 5;
    doc.text(params.churchName, 20, y);
  }

  // Clerk notes
  if (params.clerkNotes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    const notesWrapped = doc.splitTextToSize(
      `Clerk Notes: ${params.clerkNotes}`,
      170
    );
    doc.text(notesWrapped, 20, y + 12);
    doc.setTextColor(0, 0, 0);
  }

  // Doc ID & dates
  drawDocIdAndDates(doc, params.requestId, generatedAt, expiryDate);

  // Footer
  drawFooter(doc);

  return doc;
}

function generateServiceCertificate(params: GenerateDocumentParams): jsPDF {
  const doc = new jsPDF();
  const memberName = resolveMemberName(params);
  const generatedAt = resolveGeneratedAt(params);
  const expiryDate = resolveExpiry(params);

  // Header
  drawHeader(doc, params.churchName);

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Service Certificate', 105, 60, { align: 'center' });

  // Decorative line
  doc.setDrawColor(26, 122, 86);
  doc.setLineWidth(0.8);
  doc.line(55, 64, 155, 64);

  // Body
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('This certificate is proudly presented to', 105, 82, {
    align: 'center',
  });

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(memberName, 105, 96, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');

  let y = 112;

  doc.text(
    'in grateful recognition and heartfelt appreciation of',
    105,
    y,
    { align: 'center' }
  );
  y += 8;

  doc.text(
    'their dedicated service and valuable contributions to',
    105,
    y,
    { align: 'center' }
  );
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(params.churchName, 105, y, { align: 'center' });
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Seventh-day Adventist Church', 105, y, { align: 'center' });

  // Location
  if (params.churchCity || params.churchCountry) {
    y += 8;
    const loc = [params.churchCity, params.churchCountry]
      .filter(Boolean)
      .join(', ');
    doc.text(loc, 105, y, { align: 'center' });
  }

  // Reason / service description
  if (params.reason) {
    y += 12;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    const reasonWrapped = doc.splitTextToSize(
      `"${params.reason}"`,
      140
    );
    doc.text(reasonWrapped, 105, y, { align: 'center' });
  }

  // Date
  y = Math.max(y + 18, 170);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date Issued: ${formatDate(generatedAt)}`, 105, y, {
    align: 'center',
  });

  // Pastor name
  if (params.pastorName) {
    y += 8;
    doc.text(`Issued by: ${params.pastorName}`, 105, y, { align: 'center' });
  }

  // Clerk notes
  if (params.clerkNotes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 100, 100);
    const notesWrapped = doc.splitTextToSize(
      `Clerk Notes: ${params.clerkNotes}`,
      140
    );
    doc.text(notesWrapped, 105, y + 15, { align: 'center' });
    doc.setTextColor(0, 0, 0);
  }

  // Signatures
  drawSignatureLine(doc, 230, 'Church Pastor');
  drawSignatureLine(doc, 230, 'Church Clerk');

  // Doc ID & dates
  drawDocIdAndDates(doc, params.requestId, generatedAt, expiryDate);

  // Footer
  drawFooter(doc);

  return doc;
}
